version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_gt
      MONGO_INITDB_ROOT_PASSWORD: Green2o21
    volumes:
      - ./data/db:/data/db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 60s

  mysql:
    restart: always
    image: mysql:8
    platform: linux/amd64
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory-service
    ports:
      - 3306:3306
